name: Build & Push to GHCR

on:
  push:
    branches: [ main ]   # 🔧 change if you deploy from another branch

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}   # will be "purbojati"
          password: ${{ secrets.GHCR_TOKEN }}        # 🔧 must have write:packages

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/purbojati/aidorama:latest        # 🔧 must match server compose
            ghcr.io/purbojati/aidorama:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}