name: Build & Push to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/purbojati/aidorama:latest
            ghcr.io/purbojati/aidorama:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}
          build-args: |
            DATABASE_URL=${{ secrets.AIDORAMA_DATABASE_URL }}
            BETTER_AUTH_SECRET=${{ secrets.AIDORAMA_BETTER_AUTH_SECRET }}
            BETTER_AUTH_URL=${{ secrets.AIDORAMA_BETTER_AUTH_URL }}
            OPENROUTER_API_KEY=${{ secrets.AIDORAMA_OPENROUTER_API_KEY }}
            R2_ENDPOINT=${{ secrets.AIDORAMA_R2_ENDPOINT }}
            R2_ACCESS_KEY_ID=${{ secrets.AIDORAMA_R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.AIDORAMA_R2_SECRET_ACCESS_KEY }}
            R2_BUCKET_NAME=${{ secrets.AIDORAMA_R2_BUCKET_NAME }}
            R2_PUBLIC_URL=${{ secrets.AIDORAMA_R2_PUBLIC_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.AIDORAMA_GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.AIDORAMA_GOOGLE_CLIENT_SECRET }}